// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR4KY-v_tan0oh-2MVvJtvujxV_Si_gew',
    appId: '1:122160735685:web:daf3070445e59ad6b317ac',
    messagingSenderId: '122160735685',
    projectId: 'subeditor-2a35b',
    authDomain: 'subeditor-2a35b.firebaseapp.com',
    storageBucket: 'subeditor-2a35b.appspot.com',
    measurementId: 'G-5DE42JVLGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApef0JFkAGeJBHZu41l78CQuN3I2FCZbY',
    appId: '1:122160735685:android:f01fc936fca18e16b317ac',
    messagingSenderId: '122160735685',
    projectId: 'subeditor-2a35b',
    storageBucket: 'subeditor-2a35b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFv0vuDhVIr0AjyOXO-lLGCuCtVX2o58',
    appId: '1:122160735685:ios:1de1e9eeeba21d27b317ac',
    messagingSenderId: '122160735685',
    projectId: 'subeditor-2a35b',
    storageBucket: 'subeditor-2a35b.appspot.com',
    iosClientId: '122160735685-8ogao94e25ueoaq80d598u2q8edl2jse.apps.googleusercontent.com',
    iosBundleId: 'com.example.subEditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKFv0vuDhVIr0AjyOXO-lLGCuCtVX2o58',
    appId: '1:122160735685:ios:8c741d5cdc830a88b317ac',
    messagingSenderId: '122160735685',
    projectId: 'subeditor-2a35b',
    storageBucket: 'subeditor-2a35b.appspot.com',
    iosClientId: '122160735685-5v56b4kpa35a798b7iofkt45s9tn2m78.apps.googleusercontent.com',
    iosBundleId: 'com.example.subEditor.RunnerTests',
  );
}
